2019-07-04 12:05:24,940 ERROR: Exception on /login [POST] [in /Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/app.py:1780
Traceback (most recent call last):
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/main_app/routes.py", line 48, in login_page
    user = User.query.filter_by(username=form.username.data).first()
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3222, in first
    ret = list(self[0:1])
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3012, in __getitem__
    return list(res)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3324, in __iter__
    return self._execute_and_instances(context)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3349, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 399, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value.with_traceback(tb)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user
[SQL: SELECT user.id AS user_id, user.username AS user_username, user.email AS user_email, user.password_hash AS user_password_hash, user.about_me AS user_about_me, user.last_seen AS user_last_seen 
FROM user 
WHERE user.username = ?
 LIMIT ? OFFSET ?]
[parameters: ('reece', 1, 0)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-07-04 12:06:14,605 INFO: Microblog startup [in /Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/main_app/__init__.py:44
2019-07-04 12:06:42,254 INFO: Microblog startup [in /Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/main_app/__init__.py:44
2019-07-04 18:11:22,036 INFO: Microblog startup [in /Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/main_app/__init__.py:44
2019-07-04 18:21:49,925 INFO: Microblog startup [in /Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/main_app/__init__.py:44
