2019-07-03 14:35:38,763 ERROR: Exception on /user/susan [GET] [in /Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/app.py:1780
Traceback (most recent call last):
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/main_app/routes.py", line 103, in user_page
    return render_template("user.html", title=title, user=user, posts=posts)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/main_app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/main_app/templates/base.html", line 39, in top-level template code
    {% block content %}
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/main_app/templates/user.html", line 18, in block "content"
    <p><a href="{{ url_for('unfollow', username=user.username) }}">Unfollow</a></p>
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2080, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 2007, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'unfollow' with values ['username']. Did you mean 'unfollowed' instead?
2019-07-03 14:36:53,284 ERROR: Exception on /user/susan [GET] [in /Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/app.py:1780
Traceback (most recent call last):
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/main_app/routes.py", line 103, in user_page
    return render_template("user.html", title=title, user=user, posts=posts)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/main_app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/main_app/templates/base.html", line 39, in top-level template code
    {% block content %}
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/main_app/templates/user.html", line 18, in block "content"
    <p><a href="{{ url_for('unfollow', username=user.username) }}">Unfollow</a></p>
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2080, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/Users/reecenicholls/OneDrive - Cowes Enterprise College/CODING/Website Stuff/microblog/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 2007, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'unfollow' with values ['username']. Did you mean 'unfollowed' instead?
